"""empty message

Revision ID: 021a6a75e148
Revises: b89b57b0ccff
Create Date: 2026-04-30 00:50:59.632482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021a6a75e148'
down_revision: Union[str, Sequence[str], None] = 'b89b57b0ccff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protected_apps', sa.Column('risk_score_severity_score_weight', sa.Float(), nullable=False))
    op.add_column('protected_apps', sa.Column('risk_score_confidence_pct_weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protected_apps', 'risk_score_confidence_pct_weight')
    op.drop_column('protected_apps', 'risk_score_severity_score_weight')
    # ### end Alembic commands ###
