"""empty message

Revision ID: 058430ac2e43
Revises: 
Create Date: 2026-04-30 15:39:28.801405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058430ac2e43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPERUSER', 'STANDARD', name='userroles'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    op.create_table('protected_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('live', sa.Boolean(), nullable=False),
    sa.Column('risk_score_severity_score_weight', sa.Float(), nullable=False),
    sa.Column('risk_score_confidence_pct_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ABS(risk_score_severity_score_weight + risk_score_confidence_pct_weight - 1.0) <= 0.000001', name=op.f('ck_protected_apps_risk_score_weights_sum')),
    sa.CheckConstraint('risk_score_confidence_pct_weight >= 0 AND risk_score_confidence_pct_weight <= 1', name=op.f('ck_protected_apps_risk_score_confidence_pct_weight_range')),
    sa.CheckConstraint('risk_score_severity_score_weight >= 0 AND risk_score_severity_score_weight <= 1', name=op.f('ck_protected_apps_risk_score_severity_score_weight_range')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_protected_apps_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protected_apps')),
    sa.UniqueConstraint('owner_user_id', 'name', 'url', name=op.f('uq_protected_apps_owner_user_id'))
    )
    op.create_table('app_security_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protected_app_id', sa.Integer(), nullable=False),
    sa.Column('http_method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', name='httpmethods'), nullable=False),
    sa.Column('route_pattern', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('MONITOR', 'ENFORCE', name='policymodes'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('active_status_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('min_block_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('min_block_score >= 0 AND min_block_score <= 100', name=op.f('ck_app_security_policies_min_block_score_range')),
    sa.CheckConstraint('priority >= 0 AND priority <= 100', name=op.f('ck_app_security_policies_priority_range')),
    sa.ForeignKeyConstraint(['protected_app_id'], ['protected_apps.id'], name=op.f('fk_app_security_policies_protected_app_id_protected_apps')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_security_policies')),
    sa.UniqueConstraint('protected_app_id', 'http_method', 'route_pattern', name=op.f('uq_app_security_policies_protected_app_id'))
    )
    op.create_table('flagged_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_security_policy_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', name='httpmethods'), nullable=False),
    sa.Column('route_path', sa.String(length=255), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('source_ip', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_security_policy_id'], ['app_security_policies.id'], name=op.f('fk_flagged_requests_app_security_policy_id_app_security_policies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flagged_requests'))
    )
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flagged_request_id', sa.Integer(), nullable=False),
    sa.Column('threat_type', sa.Enum('NONE', 'UNKNOWN', 'SQLi', 'XSS', 'PATH_TRAVERSAL', name='threattypes'), nullable=False),
    sa.Column('threat_severity', sa.Enum('NONE', 'LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='threatseverities'), nullable=False),
    sa.Column('confidence_pct', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ALLOW', 'BLOCK', 'MONITOR_ONLY', name='securityactions'), nullable=False),
    sa.Column('reason_desc', sa.String(length=1500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_pct >= 0 AND confidence_pct <= 100', name=op.f('ck_security_events_confidence_pct_range')),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name=op.f('ck_security_events_risk_score_range')),
    sa.ForeignKeyConstraint(['flagged_request_id'], ['flagged_requests.id'], name=op.f('fk_security_events_flagged_request_id_flagged_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_events')
    op.drop_table('flagged_requests')
    op.drop_table('app_security_policies')
    op.drop_table('protected_apps')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
