"""empty message

Revision ID: 1e5fe15d5fc1
Revises: c791b77f7291
Create Date: 2026-05-04 22:40:02.756764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e5fe15d5fc1'
down_revision: Union[str, Sequence[str], None] = 'c791b77f7291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flagged_requests', 'app_security_policy_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flagged_requests', 'app_security_policy_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
