"""empty message

Revision ID: 8a1b3ba2ca77
Revises: 907b9a8e9f56
Create Date: 2026-04-28 18:24:40.523088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1b3ba2ca77'
down_revision: Union[str, Sequence[str], None] = '907b9a8e9f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_protected_apps_owner_user_id'), 'protected_apps', ['owner_user_id', 'name', 'url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_protected_apps_owner_user_id'), 'protected_apps', type_='unique')
    # ### end Alembic commands ###
