"""empty message

Revision ID: f6a1dfbe6633
Revises: 5ffd7df523d4
Create Date: 2026-04-09 10:28:51.315690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a1dfbe6633'
down_revision: Union[str, Sequence[str], None] = '5ffd7df523d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repository_url', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(length=96), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('threat_type', sa.Enum('XSS', 'SQLi', 'WEAK_HASH', 'WEAK_PASSWORDS', 'NONE', name='evidencethreattypes'), nullable=False),
    sa.Column('confidence_level', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MODERATE', 'LOW', 'NONE', name='evidenceseverities'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('scans')
    # ### end Alembic commands ###
